/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package management.information.system;

/**
 *
 * @author Drew
 */
public class Access extends javax.swing.JFrame {

    private boolean isLogin = true;
    
    /**
     * Creates new form Access
     */
    public Access() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        access_tabpane = new javax.swing.JTabbedPane();
        access_login_panel = new javax.swing.JPanel();
        access_login_lbl = new javax.swing.JLabel();
        access_login_passwordF = new javax.swing.JPasswordField();
        access_login_usernameF = new javax.swing.JTextField();
        access_login_enter = new javax.swing.JButton();
        access_login_checkB = new javax.swing.JCheckBox();
        access_register_toRegister = new javax.swing.JLabel();
        access_register_panel = new javax.swing.JPanel();
        access_register_lbl = new javax.swing.JLabel();
        access_register_passwordF = new javax.swing.JPasswordField();
        access_register_usernameF = new javax.swing.JTextField();
        access_login_enter1 = new javax.swing.JButton();
        access_register_confirmPasswordF = new javax.swing.JPasswordField();
        access_register_checkB1 = new javax.swing.JCheckBox();
        access_register_toLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        access_tabpane.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        access_login_lbl.setText("Login");

        access_login_passwordF.setText("jPasswordField1");
        access_login_passwordF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                access_login_passwordFActionPerformed(evt);
            }
        });

        access_login_usernameF.setText("jTextField1");

        access_login_enter.setText("Enter");
        access_login_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                access_login_enterActionPerformed(evt);
            }
        });

        access_login_checkB.setLabel("Show Password");

        access_register_toRegister.setText("Dont have an Account? Click HERE to Register");
        access_register_toRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                access_register_toRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout access_login_panelLayout = new javax.swing.GroupLayout(access_login_panel);
        access_login_panel.setLayout(access_login_panelLayout);
        access_login_panelLayout.setHorizontalGroup(
            access_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, access_login_panelLayout.createSequentialGroup()
                .addGap(0, 110, Short.MAX_VALUE)
                .addGroup(access_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, access_login_panelLayout.createSequentialGroup()
                        .addGroup(access_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(access_login_panelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(access_login_checkB, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(access_login_passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(access_login_usernameF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, access_login_panelLayout.createSequentialGroup()
                        .addComponent(access_register_toRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
            .addGroup(access_login_panelLayout.createSequentialGroup()
                .addGroup(access_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(access_login_panelLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(access_login_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(access_login_panelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(access_login_enter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        access_login_panelLayout.setVerticalGroup(
            access_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(access_login_panelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(access_login_lbl)
                .addGap(18, 18, 18)
                .addComponent(access_login_usernameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(access_login_passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(access_login_checkB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(access_register_toRegister)
                .addGap(18, 18, 18)
                .addComponent(access_login_enter)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        access_tabpane.addTab("Login", access_login_panel);

        access_register_lbl.setText("Register");

        access_register_passwordF.setText("jPasswordField1");
        access_register_passwordF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                access_register_passwordFActionPerformed(evt);
            }
        });

        access_register_usernameF.setText("jTextField1");

        access_login_enter1.setText("Enter");
        access_login_enter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                access_login_enter1ActionPerformed(evt);
            }
        });

        access_register_confirmPasswordF.setText("jPasswordField1");
        access_register_confirmPasswordF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                access_register_confirmPasswordFActionPerformed(evt);
            }
        });

        access_register_checkB1.setLabel("Show Password");

        access_register_toLogin.setText("Already have an Account? Click HERE to Log-in");
        access_register_toLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                access_register_toLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout access_register_panelLayout = new javax.swing.GroupLayout(access_register_panel);
        access_register_panel.setLayout(access_register_panelLayout);
        access_register_panelLayout.setHorizontalGroup(
            access_register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(access_register_panelLayout.createSequentialGroup()
                .addGroup(access_register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(access_register_panelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(access_register_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(access_register_panelLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(access_register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(access_register_checkB1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(access_register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(access_register_usernameF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(access_register_passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(access_register_confirmPasswordF, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(access_register_panelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(access_register_toLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(access_register_panelLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(access_login_enter1)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        access_register_panelLayout.setVerticalGroup(
            access_register_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(access_register_panelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(access_register_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(access_register_usernameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(access_register_passwordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(access_register_confirmPasswordF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(access_register_checkB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(access_register_toLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(access_login_enter1)
                .addGap(24, 24, 24))
        );

        access_tabpane.addTab("Register", access_register_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(access_tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(access_tabpane, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void access_register_toLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_access_register_toLoginMouseClicked
        updateAccessState();
    }//GEN-LAST:event_access_register_toLoginMouseClicked

    private void access_register_confirmPasswordFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_access_register_confirmPasswordFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_access_register_confirmPasswordFActionPerformed

    private void access_login_enter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_access_login_enter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_access_login_enter1ActionPerformed

    private void access_register_passwordFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_access_register_passwordFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_access_register_passwordFActionPerformed

    private void access_register_toRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_access_register_toRegisterMouseClicked
        updateAccessState();
    }//GEN-LAST:event_access_register_toRegisterMouseClicked

    private void access_login_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_access_login_enterActionPerformed
        new Main_Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_access_login_enterActionPerformed

    private void access_login_passwordFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_access_login_passwordFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_access_login_passwordFActionPerformed

    private void updateAccessState(){
        isLogin = !isLogin;
        
        if(isLogin){
           access_tabpane.setSelectedIndex(1);
        }
        else{
           access_tabpane.setSelectedIndex(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Access().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox access_login_checkB;
    private javax.swing.JButton access_login_enter;
    private javax.swing.JButton access_login_enter1;
    private javax.swing.JLabel access_login_lbl;
    private javax.swing.JPanel access_login_panel;
    private javax.swing.JPasswordField access_login_passwordF;
    private javax.swing.JTextField access_login_usernameF;
    private javax.swing.JCheckBox access_register_checkB1;
    private javax.swing.JPasswordField access_register_confirmPasswordF;
    private javax.swing.JLabel access_register_lbl;
    private javax.swing.JPanel access_register_panel;
    private javax.swing.JPasswordField access_register_passwordF;
    private javax.swing.JLabel access_register_toLogin;
    private javax.swing.JLabel access_register_toRegister;
    private javax.swing.JTextField access_register_usernameF;
    private javax.swing.JTabbedPane access_tabpane;
    // End of variables declaration//GEN-END:variables
}
